version: "3"

services:
  php-fpm:
    build:
      context: etc/devel/docker/php-fpm
    image: app/php-fpm
    container_name: app.php-fpm
    volumes:
      - ".:/app"
    
  nginx:
    build:
      context: etc/devel/docker/nginx
    image: app/nginx
    container_name: app.nginx
    volumes:
      - "./assets:/var/www/"
    ports:
      - 80:80

  mysql:
    build:
      context: etc/devel/docker/mysql
    image: app/mysql
    container_name: app.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306

  swagger_ui:
    environment:
      - SWAGGER_JSON=./assets/docs/products-api.yml
      - API_URL=http://localhost/docs/products-api.yml
    image: swaggerapi/swagger-ui
    container_name: app.swagger
    volumes:
      - "./assets/docs/products-api.yml:/usr/share/nginx/html/products-api.yml"
    ports:
      - 8080:8080